server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pwd@demo
    url: jdbc:log4jdbc:mysql://localhost:3306/sell?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true